stages:
  - lint
  - document
  - build
  - test
  - release
  - configure
  - deploy

# https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines
.if-default-branch-refs: &if-default-branch-refs
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.if-tag: &if-tag
  if: '$CI_COMMIT_TAG'

.if-merge-request: &if-merge-request
  if: '$CI_MERGE_REQUEST_IID'

# Workflow
###########
workflow:
  rules:
    - <<: *if-tag
      variables:
        # Override the IMAGE_SHA variable on tag pipelines to avoid both the default
        # branch pipeline and tag pipeline overriding each other's images arbitrarily when
        # they are both running at the same time on master.
        IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    - <<: *if-default-branch-refs
    - <<: *if-merge-request

include:
  - project: 'labs/salt-automation'
    file:
      - '/gitlab-ci-templates/common/rules.v1.yml'
      - '/gitlab-ci-templates/common/saltbert.v1.yml'
      - '/gitlab-ci-templates/common/config-updater-meta.v1.yml'
      - '/gitlab-ci-templates/common/docker-build.v1.yml'


variables:
  IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  IMAGE_DEV: magentaaps/ressourcerenter:dev
  IMAGE_TAG: magentaaps/ressourcerenter:${CI_COMMIT_TAG}
  DOCKERFILE: $CI_PROJECT_DIR/docker/Dockerfile


# Lint stage
#############
.lint-default:
  stage: lint
  needs: []
  image: python:3.8

Lint Python:
  extends:
    - .lint-default
  before_script:
    - pip3 install flake8
    - pip3 install black
  script:
    - flake8 --ignore E501,E226,W503 ressourcerenter
    - black --check --diff --exclude=migrations ressourcerenter/

Lint Dockerfiles:
  extends:
    - .lint-default
  image: hadolint/hadolint:v2.12.0-debian
  script:
    - hadolint $CI_PROJECT_DIR/docker/Dockerfile

Lint REUSE compliance:
  extends: .lint-default
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint

# Documentation stage
#####################

Generate documentation:
  stage: document
  needs: []
  image:
    name: pandoc/latex
    entrypoint: ["/bin/sh", "-c"]
  script:
    - cd admin-manual  # Matches folder in this git repo
    - pandoc manual.md -V geometry:margin=30mm --output=manual.pdf
  artifacts:
    paths:
      - admin-manual/manual.pdf

# Test stage
############
.test-default: &test-default
  stage: test
  dependencies: []
  image: ${IMAGE_SHA}
  needs:
    - Build  # from docker-build.v1.yml
  variables:
    SECRET_KEY: e$s6@0(hs5ja79-&!l7vt^onoe4h^*bv_e4hj&wt5^8*&x76-$
    TIMEZONE: Europe/Copenhagen
    POSTGRES_USER: ressourcerenter
    POSTGRES_PASSWORD: ressourcerenter
    POSTGRES_DB: ressourcerenter
    POSTGRES_HOST: ressourcerenter-db
    LANGUAGE_COOKIE_DOMAIN: localhost
    # No fiddling with sftp server during testing
    LOGIN_MOCK: cvr
    PRISME_PUSH_MOCK: "true"
    PITU_MOCK: "true"
    SAML_ENABLED: "true"
    SAML_SP_ENTITY_ID: http://localhost:8000/saml/metadata/
    SAML_SP_LOGIN_CALLBACK_URI: http://localhost:8000/login/callback
    SAML_SP_LOGOUT_CALLBACK_URI: http://localhost:8000/logout/callback/
    SAML_SP_CERTIFICATE: /ssl/sp/selfsigned.crt
    SAML_SP_KEY: /ssl/sp/selfsigned.key
    SAML_IDP_ENTITY_ID: http://localhost:8080/simplesaml/saml2/idp/metadata.php
    SAML_IDP_LOGIN_URI: http://localhost:8080/simplesaml/saml2/idp/SSOService.php
    SAML_IDP_LOGOUT_URI: http://localhost:8080/simplesaml/saml2/idp/SingleLogoutService.php
    SAML_IDP_CERTIFICATE: /ssl/idp/selfsigned.crt
    SAML_IDP_METADATA: http://localhost:8080/simplesaml/saml2/idp/metadata.php
    SAML_CONTACT_TECHNICAL_NAME: Tester
    SAML_CONTACT_TECHNICAL_EMAIL: test@example.com
    SAML_CONTACT_SUPPORT_NAME: Tester
    SAML_CONTACT_SUPPORT_EMAIL: test@example.com
    SKIP_IDP_METADATA: "true"
    GENERATE_DB_DOCUMENTATION: "false"
    ALLOWED_HOSTS: '["*"]'

Unittest:
  <<: *test-default
  services:
    - name: postgres:13
      alias: ressourcerenter-db
  script:
    - cd /app
    - coverage run manage.py test --parallel
    - coverage combine
    - coverage report --show-missing --fail-under=66
    - coverage xml
  coverage: '/^TOTAL.+?(\d+\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: /app/coverage.xml

Django check:
  <<: *test-default
  script:
    - cd /app && python manage.py check administration indberetning

# Release stage
###############

Release image:
  stage: release
  image: alpine
  needs: ["Unittest"]
  variables:
    GIT_STRATEGY: none # We do not need the source code
  dependencies: []
  extends:
    - .rules:semver-all
  before_script:
    - apk add skopeo
  script:
    - skopeo copy
      --src-creds=${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}
      --dest-creds=${RELEASE_REGISTRY_USER}:${RELEASE_REGISTRY_PASSWORD}
      "docker://${IMAGE_SHA}"
      "docker://${IMAGE_TAG}"


# Deploy stage
##############

Configure test:
  stage: configure
  extends:
    - .rules:semver-all
    - .config:endpoint-with-tag
  needs: ["Release image"]
  variables:
    # Matches routing in config-updater/config_updater/ressourcerenter/main.py in salt repo
    ENDPOINT: ressourcerenter/salt/update-test


Configure production:
  stage: configure
  extends:
    - .rules:semver-core
    - .config:endpoint-with-tag
  needs: ["Release image"]
  variables:
    # Matches routing in config-updater/config_updater/ressourcerenter/main.py in salt repo
    ENDPOINT: ressourcerenter/salt/update-production


Deploy test:
  stage: deploy
  when: manual
  extends:
    - .saltbert
    - .rules:semver-all
  variables:
    SALTBERT_ORCHESTRATION: groenland.ressourcerenter.service-test
    SALTBERT_URL: https://saltmaster.groenland.magentahosted.dk
  needs: ["Release image", "Configure test"]
  environment:
    name: test
    url: "https://test.aalisakkat.aka.sullissivik.gl"


Deploy production:
  stage: deploy
  when: manual
  extends:
    - .saltbert
    - .rules:semver-core
  variables:
    SALTBERT_ORCHESTRATION: groenland.ressourcerenter.service-prod
    SALTBERT_URL: https://saltmaster.groenland.magentahosted.dk
  needs: ["Release image", "Configure production"]
  environment:
    name: production
    url: "https://aalisakkat.aka.sullissivik.gl"
