stages:
  - lint
  - build
  - test
  - release
  - deploy

variables:
  IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  IMAGE_DEV: magentaaps/ressourcerenter:dev


# Lint stage
#############
.lint-default: &lint-default
  stage: lint
  needs: []
  image: python:3.8
  tags:
    - docker

Lint Python:
  <<: *lint-default
  before_script:
    - pip3 install flake8
  script:
    - flake8 --ignore E501,E226 ressourcerenter

Lint Dockerfiles:
  <<: *lint-default
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint $CI_PROJECT_DIR/docker/Dockerfile

# Build stage
#############

Build ressourcerenter image:
  stage: build
  needs: []
  dependencies: []
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.16.0
    entrypoint: [""]
  tags:
    - docker
  script:
    # Login to GitLab registry
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --cache
      --context=$CI_PROJECT_DIR
      --dockerfile=$CI_PROJECT_DIR/docker/Dockerfile
      --destination=${IMAGE_SHA}

# Test stage
############
.test-default: &test-default
  stage: test
  dependencies: []
  tags:
    - docker

Aalisakkat Unittest:
  <<: *test-default
  needs: ["Build ressourcerenter image"]
  image: ${IMAGE_SHA}
  services:
    - name: postgres:13
      alias: ressourcerenter-db
  variables:
    DJANGO_SECRET_KEY: e$s6@0(hs5ja79-&!l7vt^onoe4h^*bv_e4hj&wt5^8*&x76-$
    DJANGO_TIMEZONE: Europe/Copenhagen
    POSTGRES_USER: ressourcerenter
    POSTGRES_PASSWORD: ressourcerenter
    POSTGRES_DB: ressourcerenter
    POSTGRES_HOST: ressourcerenter-db
    # No fiddling with sftp server during testing
    LOGIN_MOCK: cvr
    PRISME_PUSH_MOCK: "true"
  script:
    - cd /app && python manage.py test

# Release stage
###############

.release-aalisakkat: &release-aalisakkat
  stage: release
  image: alpine
  needs: ["Aalisakkat Unittest"]
  variables:
    GIT_STRATEGY: none # We do not need the source code
  dependencies: []
  tags:
    - docker
  before_script:
    # install skopeo
    - apk add skopeo

Release aalisakkat dev image:
  <<: *release-aalisakkat
  only:
    refs:
      - master
  script:
    - skopeo copy
      --src-creds=${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
      --dest-creds=${RELEASE_REGISTRY_USER}:${RELEASE_REGISTRY_PASSWORD}
      "docker://${IMAGE_SHA}"
      "docker://${IMAGE_DEV}"


# Deploy stage
##############

.deploy-default: &deploy-default
  stage: deploy
  image: magentalabs/pepper:latest
  services: []
  dependencies: []
  tags:
    - deploy


Deploy test:
  # Automatic deployment of branch master to test
  <<: *deploy-default
  needs: ["Release aalisakkat dev image"]
  only:
    refs:
      - master
  when: manual
  variables:
    DEPLOYMENT_NAMESPACE: ressourcerenter.service-test
    SALTAPI_URL: https://ctrldev1.magenta-aps.dk/api/
    SALTAPI_EAUTH: file
    GIT_STRATEGY: none
  script:
    - echo Attempting to call deployment
    - pepper --client runner --fail-any state.orchestrate ${DEPLOYMENT_NAMESPACE}
  environment:
    name: test
    url: "https://test.aalisakkat.aka.sullissivik.gl/"
