stages:
  - lint
  - document
  - build
  - test
  - release
  - deploy


include:
  - project: 'labs/salt-automation'
    file:
      - '/gitlab-ci-templates/common/rules.v1.yml'
      - '/gitlab-ci-templates/common/saltbert.v1.yml'
      - '/gitlab-ci-templates/common/config-updater-meta.v1.yml'


variables:
  IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  IMAGE_DEV: magentaaps/ressourcerenter:dev
  IMAGE_TAG: magentaaps/ressourcerenter:${CI_COMMIT_TAG}


# Lint stage
#############
.lint-default:
  stage: lint
  needs: []
  image: python:3.8
  tags:
    - docker

Lint Python:
  extends:
    - .lint-default
  before_script:
    - pip3 install flake8
    - pip3 install black
  script:
    - flake8 --ignore E501,E226,W503 ressourcerenter
    - black --check --diff --exclude=migrations ressourcerenter/

Lint Dockerfiles:
  extends:
    - .lint-default
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint $CI_PROJECT_DIR/docker/Dockerfile

Lint REUSE compliance:
  extends: .lint-default
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint

# Build stage
#############

Build ressourcerenter image:
  stage: build
  needs: []
  dependencies: []
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.16.0
    entrypoint: [""]
  tags:
    - docker
  script:
    # Login to GitLab registry
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --cache
      --context=$CI_PROJECT_DIR
      --dockerfile=$CI_PROJECT_DIR/docker/Dockerfile
      --destination=${IMAGE_SHA}

# Test stage
############
.test-default:
  stage: test
  dependencies: []
  tags:
    - docker

Unittest:
  extends:
    - .test-default
  needs:
    - Build ressourcerenter image
  image: ${IMAGE_SHA}
  services:
    - name: postgres:13
      alias: ressourcerenter-db
  variables:
    DJANGO_SECRET_KEY: e$s6@0(hs5ja79-&!l7vt^onoe4h^*bv_e4hj&wt5^8*&x76-$
    DJANGO_TIMEZONE: Europe/Copenhagen
    POSTGRES_USER: ressourcerenter
    POSTGRES_PASSWORD: ressourcerenter
    POSTGRES_DB: ressourcerenter
    POSTGRES_HOST: ressourcerenter-db
    # No fiddling with sftp server during testing
    LOGIN_MOCK: cvr
    PRISME_PUSH_MOCK: "true"
    PITU_MOCK: "true"
  script:
    - cd /app && python manage.py test

# Documentation stage
#####################

Generate documentation:
  stage: document
  needs: []
  image:
    name: pandoc/latex
    entrypoint: ["/bin/sh", "-c"]
  script:
    - cd manual
    - pandoc manual.md -V geometry:margin=30mm --output=manual.pdf
  artifacts:
    paths:
      - manual/manual.pdf


# Release stage
###############

.release-aalisakkat:
  stage: release
  image: alpine
  needs:
    - Unittest
  variables:
    GIT_STRATEGY: none # We do not need the source code
  dependencies: []
  tags:
    - docker
  before_script:
    # install skopeo
    - apk add skopeo

Release dev image:
  extends:
    - .release-aalisakkat
  only:
    refs:
      - master
  script:
    - skopeo copy
      --src-creds=${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
      --dest-creds=${RELEASE_REGISTRY_USER}:${RELEASE_REGISTRY_PASSWORD}
      "docker://${IMAGE_SHA}"
      "docker://${IMAGE_DEV}"

Release prod image:
  extends:
    - .release-aalisakkat
    - .rules:semver-all
  script:
    - skopeo copy
      --src-creds=${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
      --dest-creds=${RELEASE_REGISTRY_USER}:${RELEASE_REGISTRY_PASSWORD}
      "docker://${IMAGE_SHA}"
      "docker://${IMAGE_TAG}"


# Deploy stage
##############

Deploy test:
  # Automatic deployment of branch master to test
  stage: deploy
  when: manual
  only:
    refs:
      - master
  extends:
    - .saltbert
  variables:
    SALTBERT_ORCHESTRATION: ressourcerenter.service-test
    SALTBERT_URL: https://ctrldev1.magenta-aps.dk
  environment:
    name: test
    url: "https://test.aalisakkat.aka.sullissivik.gl"


Deploy prod:
  stage: deploy
  when: manual
  extends:
    - .saltbert
    - .rules:semver-all
  variables:
    SALTBERT_ORCHESTRATION: ressourcerenter.service-prod
    SALTBERT_URL: https://ctrl1.magenta-aps.dk
  needs: ["Release prod image"]
  environment:
    name: production
    url: "https://aalisakkat.aka.sullissivik.gl"
