version: "3.4"
services:
  ressourcerenter-web:
    container_name: ressourcerenter
    image: ressourcerenter:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - ./dev-environment/ressourcerenter.env
    volumes:
      - ./ressourcerenter/:/app
      - ./data/:/srv/media
      - ./dev-environment/cert:/ssl:ro
    environment:
      - MAKE_MIGRATIONS=true
    command: gunicorn --bind=0.0.0.0:8000 project.wsgi:application --reload --workers=1 --access-logfile - --error-logfile - --capture-output

  postgres:
    container_name: ressourcerenter-db
    image: postgres:13
    ports:
      # expose to localhost for easier debugging
      - "5432:5432"
    env_file:
      - ./dev-environment/ressourcerenter.env
    volumes:
      - ressourcerenter-postgres-data:/var/lib/postgresql/data

  ressourcerenter-cron:
    container_name: ressourcerenter-cron
    image: ressourcerenter:latest
    depends_on:
      - postgres
    env_file:
      - ./dev-environment/ressourcerenter.env
    volumes:
      - ./ressourcerenter/:/app
      - ./data/:/srv/media
      - ./dev-environment/crontab:/crontab
    entrypoint: [ ]
    command: [ "supercronic", "/crontab" ]

  test-idp:
    user: "1000:1000"
    image: kenchan0130/simplesamlphp
    container_name: idp
    ports:
      - "8888:8080"
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://localhost:8000/indberetning/metadata/
      # SIMPLESAMLPHP_SP_ENTITY_ID: http://aalisakkat.aka.nanoq.gl
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:8000/indberetning/login/callback/
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost:8000/indberetning/logout/callback/
      #SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:8888/simplesaml/module.php/saml/sp/saml2-acs.php/example-userpass
      #SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost:8888/simplesaml/module.php/saml/sp/saml2-logout.php/example-userpass

    volumes:
      - ./dev-environment/cert/idp:/var/www/simplesamlphp/cert:ro
      - ./dev-idp/authsources.php:/var/www/simplesamlphp/config/authsources.php


volumes:
  ressourcerenter-postgres-data:
