version: "3.4"
services:
  ressourcerenter-web:
    container_name: ressourcerenter
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - ./dev-environment/ressourcerenter.env
    volumes:
      - ./ressourcerenter/:/app
      # TODO: REMOVE LATER
      - ./dev-environment/certs/private/apache-selfsigned.key:/etc/ssl/pitu/key.pem
      - ./dev-environment/certs/public/apache-selfsigned.crt:/etc/ssl/pitu/certificate.crt
      - ./dev-environment/certs/remote/pitu_https_certificate.crt:/etc/ssl/proxy/knno_root_ca.cert
    environment:
      - MAKE_MIGRATIONS=true
      - MIGRATE=true
    command: gunicorn --bind=0.0.0.0:8000 project.wsgi:application --reload --workers=1 --access-logfile - --error-logfile - --capture-output

  postgres:
    container_name: ressourcerenter-db
    image: postgres:13
    ports:
      # expose to localhost for easier debugging
      - "5432:5432"
    env_file:
      - ./dev-environment/ressourcerenter.env
    volumes:
      - ressourcerenter-postgres-data:/var/lib/postgresql/data

volumes:
  ressourcerenter-postgres-data:
