version: "3.4"
services:
  ressourcerenter-web:
    container_name: ressourcerenter
    image: ressourcerenter:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
    network_mode: "host"
    env_file:
      - ./dev-environment/ressourcerenter.env
    volumes:
      - ./ressourcerenter/:/app
      - ./data/g69export:/srv/media/g69export
      - ./data/bilag:/srv/media/bilag
      - ./data/:/app/project/static/media
      - ./manual/:/app/project/static/media/manual
      - ./dev-environment/cert:/ssl:ro
    command: bash -c "
      django-admin compilemessages &&
      gunicorn --bind=0.0.0.0:8000 project.wsgi:application --reload --workers=1 --access-logfile - --error-logfile - --capture-output
      "

  postgres:
    container_name: ressourcerenter-db
    image: postgres:13
    network_mode: "host"
    env_file:
      - ./dev-environment/ressourcerenter.env
    volumes:
      - ressourcerenter-postgres-data:/var/lib/postgresql/data

  ressourcerenter-cron:
    container_name: ressourcerenter-cron
    image: ressourcerenter:latest
    network_mode: "host"
    depends_on:
      - postgres
    env_file:
      - ./dev-environment/ressourcerenter.env
    volumes:
      - ./ressourcerenter/:/app
      - ./data/:/srv/media
      - ./dev-environment/crontab:/crontab
    entrypoint: [ ]
    command: [ "supercronic", "/crontab" ]

  manual:
    container_name: ressourcerenter-manual
    image: pandoc/latex
    volumes:
      - ./manual/:/data
    # options for the -V parameter: https://pandoc.org/MANUAL.html#templates
    command: [ "manual.md", "-V", "geometry:margin=30mm", "-o", "administration-manual.pdf" ]

  ressourcerenter-test-idp:
    user: "1000:1000"
    image: kenchan0130/simplesamlphp
    container_name: ressourcerenter-test-idp
    network_mode: "host"
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://localhost:8000/saml/metadata/
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:8000/login/callback/
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost:8000/logout/callback/
      SIMPLESAMLPHP_IDP_CERTIFICATE: /var/www/simplesamlphp/cert/selfsigned.crt
      SIMPLESAMLPHP_IDP_PRIVATEKEY: /var/www/simplesamlphp/cert/selfsigned.key

    volumes:
      - ./dev-environment/cert/idp/selfsigned.crt:/var/www/simplesamlphp/cert/server.crt:ro
      - ./dev-environment/cert/idp/selfsigned.key:/var/www/simplesamlphp/cert/server.pem:ro
      - ./dev-idp/authsources.php:/var/www/simplesamlphp/config/authsources.php:ro
      - ./dev-idp/saml20-sp-remote.php:/var/www/simplesamlphp/metadata/saml20-sp-remote.php:ro


volumes:
  ressourcerenter-postgres-data:
