# Generated by Django 3.2.9 on 2021-11-22 14:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afgiftsperiode',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('navn', models.TextField(default='')),
                ('vis_i_indberetning', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['aarkvartal__aar', 'aarkvartal__kvartal'],
            },
        ),
        migrations.CreateModel(
            name='BeregningsModel2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('transport_afgift_rate', models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True, verbose_name='Transportafgift i procent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fangst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pris', models.DecimalField(decimal_places=2, default='0.0', max_digits=12)),
                ('vaegt', models.DecimalField(decimal_places=2, default='0.0', max_digits=10)),
                ('fartoej_groenlandsk', models.BooleanField(default=True)),
                ('til_export', models.BooleanField(default=True)),
                ('overfoert_til_tredje_part', models.BooleanField(default=False)),
                ('export_inkluderet_i_pris', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FangstType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('navn', models.TextField(max_length=2048)),
                ('beskrivelse', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FiskeArt',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('navn', models.TextField(unique=True)),
                ('beskrivelse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('navn', models.TextField(unique=True)),
                ('beskrivelse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kvartal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aar', models.PositiveSmallIntegerField(db_index=True, help_text='År', verbose_name='År')),
                ('kvartal', models.PositiveSmallIntegerField(db_index=True, help_text='Kvartal', validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=4)], verbose_name='Kvartal')),
                ('dato_fra', models.DateField(null=True)),
                ('dato_til', models.DateField(null=True)),
            ],
            options={
                'ordering': ['aar', 'kvartal'],
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fangsttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.fangsttype')),
                ('fiskeart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.fiskeart')),
            ],
        ),
        migrations.CreateModel(
            name='SatsTabelElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_pr_kg_indhandling', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rate_pr_kg_export', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rate_procent_indhandling', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rate_procent_export', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rate_prkg_groenland', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rate_prkg_udenlandsk', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ressource')),
                ('tabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='administration.afgiftsperiode')),
            ],
        ),
        migrations.CreateModel(
            name='FangstAfgift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afgift', models.DecimalField(decimal_places=2, default='0.0', max_digits=12)),
                ('beregnings_model_id', models.PositiveIntegerField(null=True)),
                ('beregnings_model_indholds_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('emne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.fangst')),
                ('rate_element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.satstabelelement')),
            ],
        ),
        migrations.AddField(
            model_name='fangst',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ressource'),
        ),
        migrations.AddField(
            model_name='afgiftsperiode',
            name='aarkvartal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.kvartal'),
        ),
    ]
