# Generated by Django 3.2.9 on 2021-12-14 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afgiftsperiode',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('navn_dk', models.TextField(max_length=2048, verbose_name='Dansk navn')),
                ('navn_gl', models.TextField(max_length=2048, verbose_name='Grønlandsk navn')),
                ('beskrivelse', models.TextField(blank=True, default='', verbose_name='Beskrivelse')),
                ('vis_i_indberetning', models.BooleanField(default=False)),
                ('dato_fra', models.DateField()),
                ('dato_til', models.DateField()),
            ],
            options={
                'ordering': ['dato_fra', 'dato_til'],
            },
        ),
        migrations.CreateModel(
            name='BeregningsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiskeArt',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('navn_dk', models.TextField(max_length=2048, unique=True, verbose_name='Dansk navn')),
                ('navn_gl', models.TextField(max_length=2048, unique=True, verbose_name='Grønlandsk navn')),
                ('beskrivelse', models.TextField()),
                ('pelagisk', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['navn_dk'],
            },
        ),
        migrations.CreateModel(
            name='SkemaType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('navn_dk', models.TextField(max_length=2048, verbose_name='Dansk navn')),
                ('navn_gl', models.TextField(max_length=2048, verbose_name='Grønlandsk navn')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BeregningsModel2021',
            fields=[
                ('beregningsmodel_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='subclass_instance', serialize=False, to='administration.beregningsmodel')),
                ('transport_afgift_rate', models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True, verbose_name='Transportafgift i procent')),
            ],
            bases=('administration.beregningsmodel',),
        ),
        migrations.CreateModel(
            name='SatsTabelElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fartoej_groenlandsk', models.BooleanField(null=True)),
                ('rate_pr_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Afgift, kr/kg')),
                ('rate_procent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Afgift, procent af salgspris')),
                ('fiskeart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.fiskeart')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='administration.afgiftsperiode')),
                ('skematype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.skematype')),
            ],
        ),
        migrations.CreateModel(
            name='ProduktType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('navn_dk', models.TextField(max_length=2048, verbose_name='Dansk navn')),
                ('navn_gl', models.TextField(max_length=2048, verbose_name='Grønlandsk navn')),
                ('beskrivelse', models.TextField(blank=True, default='', verbose_name='Beskrivelse')),
                ('fartoej_groenlandsk', models.BooleanField(null=True)),
                ('fiskeart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.fiskeart')),

            ],
            options={
                'ordering': ('navn_dk',)
            },
        ),
        migrations.CreateModel(
            name='HistoricalSatsTabelElement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fartoej_groenlandsk', models.BooleanField(null=True)),
                ('rate_pr_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Afgift, kr/kg')),
                ('rate_procent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Afgift, procent af salgspris')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fiskeart', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.fiskeart')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('periode', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.afgiftsperiode')),
                ('skematype', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.skematype')),
            ],
            options={
                'verbose_name': 'historical sats tabel element',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFiskeArt',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('navn_dk', models.TextField(db_index=True, max_length=2048, verbose_name='Dansk navn')),
                ('navn_gl', models.TextField(db_index=True, max_length=2048, verbose_name='Grønlandsk navn')),
                ('beskrivelse', models.TextField()),
                ('pelagisk', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fiske art',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAfgiftsperiode',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('navn_dk', models.TextField(max_length=2048, verbose_name='Dansk navn')),
                ('navn_gl', models.TextField(max_length=2048, verbose_name='Grønlandsk navn')),
                ('beskrivelse', models.TextField(blank=True, default='', verbose_name='Beskrivelse')),
                ('vis_i_indberetning', models.BooleanField(default=False)),
                ('dato_fra', models.DateField()),
                ('dato_til', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('beregningsmodel', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.beregningsmodel')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical afgiftsperiode',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='fiskeart',
            name='skematype',
            field=models.ManyToManyField(to='administration.SkemaType'),
        ),
        migrations.CreateModel(
            name='FangstAfgift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afgift', models.DecimalField(decimal_places=2, default='0.0', max_digits=12)),
                ('rate_procent', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('rate_pr_kg', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('beregningsmodel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.beregningsmodel')),
            ],
        ),
    ]
