# Generated by Django 3.2.9 on 2021-12-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indberetning', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fangstafgift',
            name='indberetninglinje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indberetning.indberetninglinje'),
        ),
    ]
