# Generated by Django 3.2.9 on 2022-01-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afgiftsperiode',
            options={'ordering': ['-dato_fra', '-dato_til']},
        ),
    ]
