# Generated by Django 3.2.9 on 2021-12-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_historical_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beregningsmodel2021',
            name='id',
        ),
        migrations.AddField(
            model_name='afgiftsperiode',
            name='beregningsmodel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.beregningsmodel'),
        ),
        migrations.AddField(
            model_name='fangstafgift',
            name='beregningsmodel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.beregningsmodel'),
        ),
        migrations.AddField(
            model_name='historicalafgiftsperiode',
            name='beregningsmodel',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.beregningsmodel'),
        ),
        migrations.AlterField(
            model_name='beregningsmodel2021',
            name='beregningsmodel_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='subclass_instance', serialize=False, to='administration.beregningsmodel'),
        ),
        migrations.AlterField(
            model_name='beregningsmodel',
            name='navn',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
