# Generated by Django 3.2.9 on 2022-01-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_afgiftsperiode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkttype',
            name='gruppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtyper', to='administration.produkttype'),
        ),
    ]
