# Generated by Django 3.2.9 on 2022-02-14 17:47

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0004_produkttype_gruppe'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiskeart',
            name='debitorgruppekode_havgående',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='fiskeart',
            name='debitorgruppekode_indhandling',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='fiskeart',
            name='debitorgruppekode_kystnært',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='historicalfiskeart',
            name='debitorgruppekode_havgående',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='historicalfiskeart',
            name='debitorgruppekode_indhandling',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='historicalfiskeart',
            name='debitorgruppekode_kystnært',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.CreateModel(
            name='Prisme10QBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('delivered', models.DateTimeField(blank=True, null=True)),
                ('delivery_error', models.TextField(blank=True, default='')),
                ('collect_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('created', 'Ikke afsendt'), ('delivering', 'Afsender'), ('failed', 'Afsendelse fejlet'), ('delivered', 'Afsendt'), ('cancelled', 'Annulleret')], default='created', max_length=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_prisme_batches', to=settings.AUTH_USER_MODEL)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_prisme_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prisme 10Q batch',
                'verbose_name_plural': 'prisme 10Q batches',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beløb', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('bogført', models.BooleanField(default=False)),
                ('kode', models.PositiveSmallIntegerField()),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.prisme10qbatch')),
                ('opretter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('periode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.afgiftsperiode')),
            ],
        ),
    ]
