# Generated by Django 3.2.9 on 2022-03-28 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0005_auto_20220223_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduktType',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('navn_dk', models.TextField(max_length=2048, verbose_name='Dansk navn')),
                ('navn_gl', models.TextField(max_length=2048, verbose_name='Grønlandsk navn')),
                ('beskrivelse', models.TextField(blank=True, default='', verbose_name='Beskrivelse')),
                ('fartoej_groenlandsk', models.BooleanField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fiskeart', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.fiskeart')),
                ('gruppe', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.produkttype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical produkt type',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
