# Generated by Django 3.2.9 on 2022-03-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20220223_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktura',
            name='opkrævningsdato',
            field=models.DateField(null=True),
        ),
    ]
