# Generated by Django 3.2.9 on 2022-03-28 12:50

import django.core.validators
from django.db import migrations, models
from django.db.models import Max


def set_fiskeart_kode(apps, schema_editor):
    FiskeArt = apps.get_model('administration', 'FiskeArt')
    current = FiskeArt.objects.aggregate(Max('kode'))['kode__max'] or 0
    for fiskeart in FiskeArt.objects.filter(kode__isnull=True).order_by('navn_dk'):
        current += 1
        fiskeart.kode = current
        fiskeart.save(update_fields=('kode',))


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_historicalprodukttype'),
        ('administration', '0006_faktura_opkrævningsdato'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiskeart',
            name='kode',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='historicalfiskeart',
            name='kode',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.RunPython(set_fiskeart_kode)
    ]
