# Generated by Django 3.2.9 on 2022-04-08 11:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indberetning', '0008_auto_20220309_1634'),
        ('administration', '0007_auto_20220328_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiskeart',
            name='debitorgruppekode_havgående',
        ),
        migrations.RemoveField(
            model_name='fiskeart',
            name='debitorgruppekode_indhandling',
        ),
        migrations.RemoveField(
            model_name='fiskeart',
            name='debitorgruppekode_kystnært',
        ),
        migrations.RemoveField(
            model_name='fiskeart',
            name='debitorgruppekode_use_skematype',
        ),
        migrations.RemoveField(
            model_name='historicalfiskeart',
            name='debitorgruppekode_havgående',
        ),
        migrations.RemoveField(
            model_name='historicalfiskeart',
            name='debitorgruppekode_indhandling',
        ),
        migrations.RemoveField(
            model_name='historicalfiskeart',
            name='debitorgruppekode_kystnært',
        ),
        migrations.RemoveField(
            model_name='historicalfiskeart',
            name='debitorgruppekode_use_skematype',
        ),
        migrations.AddField(
            model_name='historicalprodukttype',
            name='aktivitetskode_havgående',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='historicalprodukttype',
            name='aktivitetskode_indhandling',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='historicalprodukttype',
            name='aktivitetskode_kystnært',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='historicalprodukttype',
            name='aktivitetskode_svalbard',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='historicalprodukttype',
            name='fangsttype',
            field=models.CharField(choices=[('havgående', 'havgående'), ('indhandling', 'indhandling'), ('kystnært', 'kystnært'), ('svalbard', 'svalbard')], default=None, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='produkttype',
            name='aktivitetskode_havgående',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='produkttype',
            name='aktivitetskode_indhandling',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='produkttype',
            name='aktivitetskode_kystnært',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='produkttype',
            name='aktivitetskode_svalbard',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='produkttype',
            name='fangsttype',
            field=models.CharField(choices=[('havgående', 'havgående'), ('indhandling', 'indhandling'), ('kystnært', 'kystnært'), ('svalbard', 'svalbard')], default=None, max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='G69Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('år', models.PositiveSmallIntegerField()),
                ('fangsttype', models.CharField(choices=[('havgående', 'havgående'), ('indhandling', 'indhandling'), ('kystnært', 'kystnært'), ('svalbard', 'svalbard')], default='indhandling', max_length=11)),
                ('kode', models.CharField(max_length=15)),
                ('produkttype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.produkttype')),
                ('sted', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indberetning.indhandlingssted')),
            ],
            options={
                'unique_together': {('år', 'produkttype', 'sted', 'fangsttype')},
            },
        ),
    ]
