# Generated by Django 3.2.9 on 2022-04-08 09:35

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20220408_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='G69CodeExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('år', models.PositiveSmallIntegerField()),
                ('excel_file', models.FileField(upload_to=administration.models.g69_export_filepath)),
            ],
        ),
    ]
