# Generated by Django 3.2.9 on 2022-04-11 12:22

import administration.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20220408_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='G69CodeExport',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('år', models.PositiveSmallIntegerField()),
                ('excel_file', models.FileField(upload_to=administration.models.g69_export_filepath)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-år', '-created_date'),
            },
        ),
    ]
