# Generated by Django 3.2.9 on 2022-04-20 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_g69codeexport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiskeart',
            name='kode',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='historicalfiskeart',
            name='kode',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
