# Generated by Django 3.2.9 on 2022-05-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_revert_initial_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprodukttype',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produkttype',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
