# Generated by Django 3.2.9 on 2022-05-30 08:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_auto_20220525_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsatstabelelement',
            name='rate_pr_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Afgift, kr/kg'),
        ),
        migrations.AlterField(
            model_name='historicalsatstabelelement',
            name='rate_procent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Afgift, procent af salgspris'),
        ),
        migrations.AlterField(
            model_name='satstabelelement',
            name='rate_pr_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Afgift, kr/kg'),
        ),
        migrations.AlterField(
            model_name='satstabelelement',
            name='rate_procent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Afgift, procent af salgspris'),
        ),
    ]
