# Generated by Django 3.2.9 on 2022-06-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_auto_20220530_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='skematype',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
