# Generated by Django 3.2.9 on 2022-06-01 09:49

from django.db import migrations


def apply_migration(apps, schema_editor):
    SkemaType = apps.get_model('administration', 'SkemaType')
    SkemaType.objects.filter(id=3).update(enabled=False)


def revert_migration(apps, schema_editor):
    SkemaType = apps.get_model('administration', 'SkemaType')
    SkemaType.objects.filter(id=3).update(enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_skematype_enabled'),
    ]

    operations = [
        migrations.RunPython(apply_migration, reverse_code=revert_migration)
    ]
