# Generated by Django 3.2.9 on 2022-08-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_beregningsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beregningsmodel2021',
            name='transport_afgift_rate',
        ),
    ]
