# Generated by Django 3.2.9 on 2023-03-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0027_update_perioder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprodukttype',
            name='fartoej_groenlandsk',
            field=models.BooleanField(null=True, verbose_name='Grønlandsk fartøj'),
        ),
        migrations.AlterField(
            model_name='produkttype',
            name='fartoej_groenlandsk',
            field=models.BooleanField(null=True, verbose_name='Grønlandsk fartøj'),
        ),
    ]
