# Generated by Django 3.2.9 on 2023-03-06 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0030_update_fiskearter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprodukttype',
            name='aktivitetskode_havgående',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='historicalprodukttype',
            name='aktivitetskode_indhandling',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='historicalprodukttype',
            name='aktivitetskode_kystnært',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='historicalprodukttype',
            name='aktivitetskode_svalbard',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='produkttype',
            name='aktivitetskode_havgående',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='produkttype',
            name='aktivitetskode_indhandling',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='produkttype',
            name='aktivitetskode_kystnært',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='produkttype',
            name='aktivitetskode_svalbard',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
