# Generated by Django 3.2.9 on 2023-03-16 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0031_auto_20230306_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiskeart',
            name='g69_overstyringskode',
            field=models.CharField(default='241126242040197', max_length=15, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.RegexValidator('^\\d+\\Z', code='invalid', message='Indtast et gyldigt heltal.')]),
        ),
        migrations.AddField(
            model_name='historicalfiskeart',
            name='g69_overstyringskode',
            field=models.CharField(default='241126242040197', max_length=15, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.RegexValidator('^\\d+\\Z', code='invalid', message='Indtast et gyldigt heltal.')]),
        ),
    ]
