# Generated by Django 3.2.9 on 2023-03-23 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0033_update_g69_overstyring'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiskeart',
            name='betalingsart',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='historicalfiskeart',
            name='betalingsart',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
