# Generated by Django 5.2.7 on 2025-11-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0045_hellefisk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalafgiftsperiode',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical afgiftsperiode', 'verbose_name_plural': 'historical afgiftsperiodes'},
        ),
        migrations.AlterModelOptions(
            name='historicalfiskeart',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical fiske art', 'verbose_name_plural': 'historical fiske arts'},
        ),
        migrations.AlterModelOptions(
            name='historicalprodukttype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical produkt type', 'verbose_name_plural': 'historical produkt types'},
        ),
        migrations.AlterModelOptions(
            name='historicalsatstabelelement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical sats tabel element', 'verbose_name_plural': 'historical sats tabel elements'},
        ),
        migrations.AlterField(
            model_name='historicalafgiftsperiode',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfiskeart',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprodukttype',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsatstabelelement',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
