# Generated by Django 3.2.9 on 2021-12-14 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import indberetning.models
import indberetning.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indberetning',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('indberetnings_type', models.TextField(choices=[('fartøj', 'Indrapportering fra fartøj'), ('pelagisk', 'Pelagisk fiskeri'), ('indhandling', 'indhandlingssted/produktionsanlæg')])),
                ('indberetters_cpr', models.TextField(validators=[indberetning.validators.validate_cpr])),
                ('indberetningstidspunkt', models.DateTimeField(auto_now_add=True)),
                ('afstemt', models.BooleanField(default=False)),
                ('administrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('afgiftsperiode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.afgiftsperiode')),
                ('skematype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.skematype')),
            ],
            options={
                'ordering': ('indberetningstidspunkt',),
            },
        ),
        migrations.CreateModel(
            name='Virksomhed',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cvr', models.TextField(unique=True, validators=[indberetning.validators.validate_cvr])),
                ('kontakt_person', models.TextField(blank=True, default='')),
                ('kontakt_email', models.EmailField(blank=True, default='', max_length=254)),
                ('kontakts_phone_nr', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='IndberetningLinje',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fartøj_navn', models.TextField(null=True)),
                ('indhandlingssted', models.TextField(null=True)),
                ('salgsvægt', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Salgsvægt (kg)')),
                ('levende_vægt', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Levende vægt/helfisk mængde (kg)')),
                ('salgspris', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Salgspris (kr.)')),
                ('transporttillæg', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Transporttillæg (kr)')),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Bonus og andet vederlag (kr)')),
                ('note', models.TextField()),
                ('indberetning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linjer', to='indberetning.indberetning')),
                ('produkttype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.produkttype')),
            ],
        ),
        migrations.AddField(
            model_name='indberetning',
            name='virksomhed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indberetning.virksomhed'),
        ),
        migrations.CreateModel(
            name='Bilag',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bilag', models.FileField(upload_to=indberetning.models.bilag_filepath)),
                ('indberetning', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bilag', to='indberetning.indberetning')),
            ],
        ),
        migrations.CreateModel(
            name='Navne',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('navn', models.TextField()),
                ('type', models.TextField(choices=[('fartøj', 'Fartøj'), ('indhandlings_sted', 'Indhandlings sted')])),
                ('virksomhed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indberetning.virksomhed')),
            ],
            options={
                'unique_together': {('navn', 'virksomhed', 'type')},
            },
        ),
    ]
