# Generated by Django 3.2.9 on 2021-11-26 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import indberetning.models
import indberetning.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_fishtypes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indberetning',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('indberetnings_type', models.TextField(choices=[('fartøj', 'Indrapportering fra fartøj'), ('pelagisk', 'Pelagisk fiskeri'), ('indhandling', 'indhandlingssted/produktionsanlæg')])),
                ('indberetters_cpr', models.TextField(validators=[indberetning.validators.validate_cpr])),
                ('indberetningstidspunkt', models.DateTimeField(auto_now_add=True)),
                ('navn', models.TextField()),
                ('administrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('afgiftsperiode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.afgiftsperiode')),
            ],
            options={
                'ordering': ('indberetningstidspunkt',),
            },
        ),
        migrations.CreateModel(
            name='Virksomhed',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cvr', models.TextField(unique=True, validators=[indberetning.validators.validate_cvr])),
                ('kontakt_person', models.TextField(blank=True, default='')),
                ('kontakt_email', models.EmailField(blank=True, default='', max_length=254)),
                ('kontakts_phone_nr', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='IndberetningLinje',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('salgsvægt', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Salgsvægt (kg)')),
                ('levende_vægt', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Levende vægt/helfisk mængde (kg)')),
                ('salgspris', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Salgspris (kr.)')),
                ('fiskeart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.fiskeart')),
                ('indberetning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linjer', to='indberetning.indberetning')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administration.produktkategori')),
            ],
        ),
        migrations.AddField(
            model_name='indberetning',
            name='virksomhed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indberetning.virksomhed'),
        ),
        migrations.CreateModel(
            name='Bilag',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bilag', models.FileField(upload_to=indberetning.models.bilag_filepath)),
                ('indberetning', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bilag', to='indberetning.indberetning')),
            ],
        ),
        migrations.CreateModel(
            name='Navne',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('navn', models.TextField()),
                ('type', models.TextField(choices=[('fartøj', 'Fartøj'), ('indhandlings_sted', 'Indhandlings sted')])),
                ('virksomhed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indberetning.virksomhed')),
            ],
            options={
                'unique_together': {('navn', 'virksomhed', 'type')},
            },
        ),
    ]
