# Generated by Django 3.2.9 on 2022-01-13 11:49

from django.db import migrations, models
import indberetning.validators


class Migration(migrations.Migration):

    dependencies = [
        ('indberetning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indberetning',
            name='indberetnings_type',
        ),
        migrations.AlterField(
            model_name='indberetning',
            name='indberetningstidspunkt',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='virksomhed',
            name='cvr',
            field=models.TextField(db_index=True, unique=True, validators=[indberetning.validators.validate_cvr], verbose_name='CVR-nummer'),
        ),
    ]
