# Generated by Django 3.2.9 on 2021-12-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indberetning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indberetninglinje',
            name='kommentar',
            field=models.TextField(default=''),
        ),
    ]
