# Generated by Django 3.2.9 on 2022-01-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indberetning', '0002_auto_20220113_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indhandlingssted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.TextField()),
                ('stedkode', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ('navn',),
            },
        ),
        migrations.AlterField(
            model_name='indberetninglinje',
            name='transporttillæg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Transporttillæg (kr)'),
        ),
        migrations.AlterField(
            model_name='indberetninglinje',
            name='indhandlingssted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indberetning.indhandlingssted'),
        ),
    ]
