# Generated by Django 3.2.9 on 2022-01-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indberetning', '0003_auto_20220118_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indberetninglinje',
            name='produktvægt',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Produktvægt (kg)'),
        ),
    ]
