# Generated by Django 3.2.9 on 2022-02-14 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20220214_1847'),
        ('indberetning', '0005_virksomhed_navn'),
    ]

    operations = [
        migrations.AddField(
            model_name='indberetninglinje',
            name='faktura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.faktura'),
        ),
        migrations.AddField(
            model_name='indberetninglinje',
            name='kode',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
