# Generated by Django 3.2.9 on 2022-02-11 12:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indberetning', '0005_virksomhed_navn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indhandlingssted',
            name='id',
        ),
        migrations.AddField(
            model_name='indhandlingssted',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        # Recreate foreign key pointing to indhandlingssted.pk, since it has been changed from id to uuid
        # If this is not done, creation of indberetningslinje objects will fail.
        migrations.RemoveField(
            model_name='indberetninglinje',
            name='indhandlingssted',
        ),
        migrations.AddField(
            model_name='indberetninglinje',
            name='indhandlingssted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indberetning.indhandlingssted'),
        ),
    ]
