# Generated by Django 3.2.9 on 2022-02-23 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20220223_1055'),
        ('indberetning', '0006_auto_20220211_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='indberetninglinje',
            name='debitorgruppekode',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indberetninglinje',
            name='faktura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linjer', to='administration.faktura'),
        ),
    ]
