# Generated by Django 3.2.9 on 2022-03-09 15:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20220223_1055'),
        ('indberetning', '0007_auto_20220223_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='indberetninglinje',
            name='indberetningstidspunkt',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='indberetninglinje',
            name='indberetningstidspunkt',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='indberetninglinje',
            name='faktura',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linje', to='administration.faktura'),
        ),
    ]
