# Generated by Django 3.2.9 on 2022-04-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indberetning', '0008_auto_20220309_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='virksomhed',
            name='sted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='indberetning.indhandlingssted'),
        ),
        migrations.AlterField(
            model_name='indhandlingssted',
            name='navn',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='indhandlingssted',
            name='stedkode',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
