# Generated by Django 3.2.9 on 2022-04-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indberetning', '0008_auto_20220309_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='virksomhed',
            name='stedkode',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='indhandlingssted',
            name='navn',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='indhandlingssted',
            name='stedkode',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
