# Generated by Django 3.2.9 on 2022-04-20 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indberetning', '0009_auto_20220407_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indhandlingssted',
            name='stedkode',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
