# Generated by Django 3.2.9 on 2022-05-18 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indberetning', '0010_alter_indhandlingssted_stedkode'),
    ]

    operations = [
        migrations.AddField(
            model_name='indhandlingssted',
            name='aktiv_til_indhandling',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='indhandlingssted',
            name='stedkode',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.RemoveField(
            model_name='virksomhed',
            name='stedkode',
        ),
        migrations.AddField(
            model_name='virksomhed',
            name='sted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indberetning.indhandlingssted'),
        ),
    ]
