# Generated by Django 3.2.9 on 2022-07-28 13:24

from django.db import migrations, models
import django.db.models.deletion
import indberetning.models


class Migration(migrations.Migration):

    dependencies = [
        ('indberetning', '0011_auto_20220518_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virksomhed',
            name='sted',
            field=models.ForeignKey(default=indberetning.models.get_virksomhed_default_sted, on_delete=django.db.models.deletion.PROTECT, to='indberetning.indhandlingssted'),
        ),
    ]
