# Generated by Django 3.2.9 on 2022-10-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indberetning', '0012_alter_virksomhed_sted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virksomhed',
            options={'ordering': ['navn']},
        ),
    ]
