# Generated by Django 3.2.9 on 2022-11-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indberetning', '0013_alter_virksomhed_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indberetninglinje',
            name='salgspris',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Salgspris (kr)'),
        ),
        migrations.AlterField(
            model_name='navne',
            name='type',
            field=models.TextField(choices=[('fartøj', 'Fartøj'), ('indhandlings_sted', 'Indhandlingssted')]),
        ),
    ]
