# Generated by Django 3.2.9 on 2023-04-18 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indberetning', '0014_auto_20221114_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='indberetninglinje',
            name='ratenummer_counter',
            field=models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
    ]
