# Generated by Django 2.2.5 on 2019-09-24 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afgiftsperiode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=2048)),
                ('beskrivelse', models.TextField(blank=True, default='')),
                ('dato_fra', models.DateField()),
                ('dato_til', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Afgiftstabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=2048)),
                ('beskrivelse', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BeregningsModelEksempel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=2048)),
                ('beskrivelse', models.TextField(blank=True, default='')),
                ('justering_A', models.IntegerField(default=5)),
                ('justering_B', models.DecimalField(decimal_places=2, default=0.1, max_digits=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BeregningsModelPrototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=2048)),
                ('beskrivelse', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FiskeArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=2048)),
                ('beskrivelse', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormularFelt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(blank=True, default='', max_length=2048)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Tal'), (2, 'Tekst'), (3, 'Valg')])),
                ('valideringsregel', models.CharField(blank=True, default='', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Indberetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpr_cvr_nummer', models.CharField(max_length=20)),
                ('navn', models.CharField(blank=True, default='', max_length=2048)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('kontonummer', models.IntegerField(null=True)),
                ('er_rederi', models.BooleanField(default=False)),
                ('rederi_navn', models.CharField(blank=True, max_length=2048, null=True)),
                ('rederi_adresse', models.CharField(blank=True, max_length=2048, null=True)),
                ('rederi_postnummer_by', models.CharField(blank=True, max_length=2048, null=True)),
                ('administrationsadresse_navn', models.CharField(blank=True, max_length=2048, null=True)),
                ('administrationsadresse_adresse', models.CharField(blank=True, max_length=2048, null=True)),
                ('administrationsadresse_postnummer_by', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=2048)),
                ('beskrivelse', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SummeretBeregnetIndberetning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justering', models.BooleanField(default=False)),
                ('afgift_til_betaling', models.DecimalField(decimal_places=2, max_digits=100)),
                ('afstemt', models.BooleanField(default=False)),
                ('bogfoert', models.BooleanField(default=False)),
                ('sendt_til_prisme', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SatsTabelPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(choices=[(False, 'Procent'), (True, 'Pr. kilo')])),
                ('vaerdi', models.FloatField()),
                ('afgiftsperiode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resmockup.Afgiftsperiode')),
                ('fiskeart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resmockup.FiskeArt')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resmockup.Kategori')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Indberetning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indberetningstidspunkt', models.DateTimeField()),
                ('afgiftsberegningstidspunkt', models.DateTimeField(default=None, null=True)),
                ('cpr_cvr', models.CharField(blank=True, default='', max_length=20)),
                ('fartoejets_navn', models.CharField(blank=True, max_length=2048, null=True)),
                ('fartoejets_hjemsted', models.CharField(blank=True, max_length=2048, null=True)),
                ('indhandlings_eller_produktionsanlaeg', models.CharField(blank=True, default='', max_length=20)),
                ('indhandlers_cpr_cvr', models.CharField(blank=True, default='', max_length=20)),
                ('levende_vaegt', models.IntegerField(blank=True, null=True)),
                ('indhandlet_vaegt', models.IntegerField(blank=True, null=True)),
                ('vederlag_dkk', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('salgspris_dkk', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('salgsmaengde_vaegt', models.IntegerField(blank=True, null=True)),
                ('yderligere_dokumentation', models.TextField(blank=True, default='')),
                ('afgiftsperiode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='resmockup.Afgiftsperiode')),
                ('fiskeart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resmockup.FiskeArt')),
                ('indberetter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resmockup.Indberetter')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resmockup.Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='BeregningsModelKategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afgiftstabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resmockup.Afgiftstabel')),
                ('beregningsmodel_eksempel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resmockup.BeregningsModelEksempel')),
                ('fisk', models.ManyToManyField(to='resmockup.FiskeArt')),
            ],
        ),
        migrations.CreateModel(
            name='BeregningsModelFormularFelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formular', models.CharField(choices=[('Formular1', 'Formular 1'), ('Formular2', 'Formular 2'), ('Formular3', 'Formular 3'), ('Formular4', 'Formular 4')], max_length=20)),
                ('beregningsmodelkategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resmockup.BeregningsModelKategori')),
                ('formularfelt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resmockup.FormularFelt')),
            ],
        ),
        migrations.AddField(
            model_name='beregningsmodeleksempel',
            name='prototype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resmockup.BeregningsModelPrototype'),
        ),
        migrations.CreateModel(
            name='BeregnetIndberetning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kladde', models.BooleanField(default=True)),
                ('simuleret', models.BooleanField(default=True)),
                ('transportpris_indgaar_i_salgspris', models.BooleanField(default=False)),
                ('omregningsfaktor', models.DecimalField(decimal_places=2, max_digits=100)),
                ('afgiftsgrundlag', models.DecimalField(decimal_places=2, max_digits=100)),
                ('afgiftstabel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='resmockup.Afgiftstabel')),
                ('beregningsmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='resmockup.BeregningsModelEksempel')),
                ('indberetning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resmockup.Indberetning')),
                ('summeret_beregnet_indberetning', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resmockup.SummeretBeregnetIndberetning')),
            ],
        ),
        migrations.CreateModel(
            name='AfgiftsTabelPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(choices=[(False, 'Procent'), (True, 'Pr. kilo')])),
                ('vaerdi', models.FloatField()),
                ('nedre', models.FloatField()),
                ('oevre', models.FloatField()),
                ('afgiftstabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='resmockup.Afgiftstabel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='afgiftstabel',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resmockup.Kategori'),
        ),
        migrations.AddField(
            model_name='afgiftsperiode',
            name='beregningsmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resmockup.BeregningsModelEksempel'),
        ),
    ]
